### ISSUE TITLE
it stopped working

### ISSUE THREAD

**Issue by waqleh** [clupasq/ChromeHttpRequestBlocker#6]
chrome Version 59.0.3071.86 (Official Build) (64-bit)
OS: Ubuntu 16.04 LTS

**Comment by clupasq** [comment]
Just tested with Chrome version 59.0.3071.109 on a 64bit Linux and it works fine.
Can you post a pattern that does not work?

**Comment by waqleh** [comment]
I tried your pattern and in the example

> *://evilsite.com/*
and it didn't work for me yesterday! However today I wanted to send you a screenshot so I deleted my patterns and only kept yours (*://evilsite.com/*) and it worked. It seams that if a pattern doesn't work, all the others don't do also.

for example try adding those 2 patterns together:

> *://*.

> *://evilsite.com/*
result:
![screenshot from 2017-06-30 09-35-37](https://user-images.githubusercontent.com/2108837/27725652-9d29cbaa-5d77-11e7-82aa-2f04b0468852.png)

**Comment by clupasq** [comment]
You are right; this is indeed a bug. I will fix it as soon as I have some spare time.
Thanks for reporting!

**Comment by clupasq** [comment]
The error was due to the fact that I was registering an even listener for the `chrome.webRequest.onBeforeRequest` event with all the specified URL patterns as a parameter. If any of the URL patterns was invalid, that registration failed, meaning no blocked requests at all (not even for the correct patters).

I just pushed an update (version 1.0.2) in which invalid patterns are marked in the UI as such and are otherwise ignored.

**Comment by waqleh** [comment]
You should probably ignore blocking your own extension also:
![screenshot from 2017-07-03 11-35-51](https://user-images.githubusercontent.com/2108837/27787063-dc4489c4-5fe3-11e7-9f6f-9280601b555e.png)
I was able to do this when I entered a wrong pattern.
